# -*- coding: utf-8 -*-
"""volume_of_circle.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvmF0whjbBe6V7piASc2t4mS4dJzoPGJ
"""

def calculate_volume_of_sphere(radius):
  pi = 3.14
  volume = (4/3) * pi * radius**3
  return volume

radius1 = 30
radius2 = 40

volume1 = calculate_volume_of_sphere(radius1)
volume2 = calculate_volume_of_sphere(radius2)

print(volume1)
print(volume2)